config/routes.rb
Rails.application.routes.draw do
  
  resources :wizard_apps, except: [:destroy]
  match '/def/:id',    to: 'wizard_apps#wizard_definition',  via: 'get'
  match '/generate/:url',    to: 'wizard_apps#generate_wizard',  via: 'get', constraints: { :url => /.*/}
  match '/generate_app',    to: 'wizard_apps#create_app',  via: 'get'
  match '/activate_app',    to: 'wizard_apps#activate_app',  via: 'get'
  match '/generate_context',    to: 'wizard_apps#create_context',  via: 'get'
  match '/generate_index',    to: 'wizard_apps#create_index',  via: 'get'
  match '/generate_index_landmark',    to: 'wizard_apps#create_index_landmark',  via: 'get'
  match '/generate_context_landmark',    to: 'wizard_apps#create_context_landmark',  via: 'get'
  match '/generate_context_attribute_for_index',    to: 'wizard_apps#create_context_attribute_for_index',  via: 'get'
  match '/generate_computed_attribute_for_index',    to: 'wizard_apps#create_computed_attribute_for_index',  via: 'get'
  match '/generate_parameter_for_context',    to: 'wizard_apps#create_parameter_for_context',  via: 'get'
  match '/generate_full_app',    to: 'wizard_apps#create_full_app',  via: 'get'
  match '/get_context_attr',    to: 'wizard_apps#get_context_attr_id',  via: 'get'
  match '/generate_attribute_context_parameters',    to: 'wizard_apps#create_attribute_context_parameters',  via: 'get'
  match '/generate_in_context_class',    to: 'wizard_apps#create_in_context_class',  via: 'get'
  match '/generate_context_anchor_attribute_for_index',    to: 'wizard_apps#create_context_anchor_attribute_for_index_wizard_testing',  via: 'get'
  match '/generate_context_anchor_attribute_for_detail_wizard_testing',    to: 'wizard_apps#create_context_anchor_attribute_for_detail_wizard_testing',  via: 'get'
  match '/generate_index_anchor_attribute_for_index_wizard_testing',    to: 'wizard_apps#create_index_anchor_attribute_for_index_wizard_testing',  via: 'get'
  match '/generate_index_anchor_attribute_for_detail_wizard_testing',    to: 'wizard_apps#create_index_anchor_attribute_for_detail_wizard_testing',  via: 'get'
  
   
  resources :ontologies, except: [:destroy, :show]
  
  match '/start/:id',  to: 'wizard_step#start', via: 'get', as: 'wizard_steps'
  match '/finish',  to: 'wizard_step#finish', via: 'get', as: 'finish_wizard_steps'
  
  
  match '/help',   to: 'static_pages#help',    via: 'get'
  
  root  'ontologies#index', id:1
  match '/index',    to: 'static_pages#index',    via: 'get'
  match '/nomenclatorChooser',    to: 'static_pages#nomenclatorChooser',    via: 'get'
  match '/window',    to: 'static_pages#windows',    via: 'get'
  match '/addOntology',    to: 'static_pages#addOntology',    via: 'get'
  
  #controls
  match '/radio-nomenclator-chooser',    to: 'partial_pages#radio-nomenclator-chooser',    via: 'get'
  match '/info-depending-on-selected-option',    to: 'partial_pages#info-depending-on-selected-option',    via: 'get'
  match '/select-nomenclator-chooser',    to: 'partial_pages#select-nomenclator-chooser',    via: 'get'
  match '/add-ontology',    to: 'partial_pages#add-ontology',    via: 'get'
  match '/selected-properties',    to: 'partial_pages#selected-properties',    via: 'get'
  match '/datatype-property-selection',    to: 'partial_pages#datatype-property-selection',    via: 'get'
  match '/radio-bottom-detail',    to: 'partial_pages#radio-bottom-detail',    via: 'get'
  match '/select-nomenclator-chooser-for-path',    to: 'partial_pages#select-nomenclator-chooser-for-path',    via: 'get'
  match '/computed-attributes',    to: 'partial_pages#computed-attributes',    via: 'get'
  match '/modal',    to: 'partial_pages#modal',    via: 'get'
  match '/radio-attribute-for-choosing',    to: 'partial_pages#radio-attribute-for-choosing',    via: 'get'
  match '/resource-detail',    to: 'partial_pages#resource-detail',    via: 'get'
  match '/detail-other-attributes-yesno',    to: 'partial_pages#detail-other-attributes-yesno',    via: 'get'
  match '/question-options',    to: 'partial_pages#question-options',    via: 'get'
  match '/radio-attribute-for-choosing-detail',    to: 'partial_pages#radio-attribute-for-choosing-detail',    via: 'get'
  match '/info-to-show',    to: 'partial_pages#info-to-show',    via: 'get'
  match '/show-scope',    to: 'partial_pages#show-scope',    via: 'get'
  match '/show-scope-detail',    to: 'partial_pages#show-scope-detail',    via: 'get'
  match '/node-name',    to: 'partial_pages#node-name',    via: 'get'
  
 end

app/models/ontology.rb
class Ontology < ActiveRecord::Base
  validates :name, presence:true
  validates :prefix, presence: true, length: { maximum: 5, minimum: 2},
            uniqueness: { case_sensitive: false }
  validates :address, presence: true
  
  before_save { self.address = address.downcase }
end

app/controllers/ontologies_controller.rb
class OntologiesController < ApplicationController
  
  def index
    @ontologies = Ontology.all
  end
  
  def new
    @ontology = Ontology.new
  end
  
  def create
    @ontology = Ontology.new(user_params)
    if @ontology.save
      flash[:success] = "Ontology created!"
      redirect_to @ontology
    else
      render 'new'
    end
  end
  
  def edit
    @ontology = Ontology.find(params[:id])
  end

  def update
    @ontology = Ontology.find(params[:id])
    if @ontology.update_attributes(user_params)
      flash[:success] = "Ontology updated"
      @ontologies = Ontology.new
      redirect_to @ontologies
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:ontology).permit(:name, :description, :prefix, :address)
    end
end

app/helpers/ontologies_helper.rb
module OntologiesHelper
end

app/views/ontologies/_ontology.html.erb
<li>
  <%= link_to ontology.prefix, edit_ontology_path(ontology) %>
  <%= ontology.address %>
</li>

app/views/ontologies/edit.html.erb
<% provide(:title, 'Edit ontology') %>
<h1>Ontology</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ontology) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :prefix %>
      <%= f.text_field :prefix %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.submit "Save ontology", class: "btn btn-large btn-primary" %>
      
      <%= link_to "Cancel", ontologies_path, class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/ontologies/index.html.erb
<% provide(:title, 'Ontologies') %>
<h1>Ontologies</h1>

<ul class="ontologies">
  <%= render @ontologies %>
</ul>

<%= link_to 'Add Ontology', new_ontology_path, class: "btn btn-large btn-primary"%>
<%= link_to 'Create application', new_wizard_app_path, class: "btn btn-large btn-primary"%>

app/views/ontologies/new.html.erb
<% provide(:title, 'Add ontology') %>
<h1>Add Ontology</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@ontology) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :prefix %>
      <%= f.text_field :prefix %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.submit "Create ontology", class: "btn btn-large btn-primary" %>
    <% end %>
    
    <%= link_to 'Back', ontologies_path %>
  </div>
</div>